### ISSUE TITLE
Incompatible with latest version of site? (2017-05)

### ISSUE THREAD

**Issue by Fironet** [Rob-ot/bleep.com-dance-all-night#1]
So I'm not sure what changed but I noticed today that playing tracks from [this release](https://bleep.com/release/82783-alice-coltrane-world-spirituality-classics-1-the-ecstatic-music-of-alice-coltrane-turiyasangitananda) (and others) fails to play the full tracks.

Can remember being able to preview whole tracks with the script only a few weeks ago so it must be a recent change on Bleep.

**Comment by Rob-ot** [comment]
I just updated the script with a working version. Let me know if you have any more issues.

Thanks for letting me know, I'm glad people are still finding this script useful!

**Comment by Fironet** [comment]
Thanks! And yeah, fan of the script :)
